# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - deploy:
          name: Deploy application with now
          command: |
            export ENV_NAME=PRODUCTION
            if [[ -z ${CIRCLE_TAG} ]]; then export ENV_NAME=STAGING; fi
            for key in $(compgen -e); do echo ${key}; done
            echo "Building for environment", ${ENV_NAME}
  update:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - deploy:
          name: Update application
          command: |
            export ENV_NAME=PRODUCTION
            if [[ -z ${CIRCLE_TAG} ]]; then export ENV_NAME=STAGING; fi
            for key in $(compgen -e); do echo ${key}; done
            echo "update - building for environment", ${ENV_NAME}

workflows:
  version: 2
  my_workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - update:
          filters:
            branches:
              only: master
            tags:
              only: /^v.*$/
          requires:
            - build
